import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Layout from "@/components/layout/layout";
import Providers from '@/components/Providers'
import { ToastContainer } from "react-toastify";
import ToastProvider from "@/components/elements/ToastProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body>
        <Providers>
          <Layout>
            {children}
            <ToastProvider />
          </Layout>
        </Providers>
      </body>
    </html>
  );
}
